version: v1
services:
  discovery:
    image: radiocat2000/reels_orbit_discovery:latest
    container_name: ReelsOrbit-discoveryService
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - ReelsOrbit

  payment-service:
    image: radiocat2000/reels_orbit_payment:latest
    container_name: ReelsOrbit-paymentService
    ports:
      - "8053:8053"
    environment:
      - SPRING_PROFILES_ACTIVE=doc
      #- gcp-project-id=reels-orbit
      #- gcp-sql-instance-connection-name=reels-orbit:asia-south2:reels-orbit-sql
      #- gcp-sql-database-name=payment
      #- gcp-credentials-location=file:/app/config/credentials.json
      #- datasource-username-CSQL=postgres
      #- datasource-password-CSQL=password
      #- eureka-default-zone=http://discovery:8761/eureka
      #- kafka-bootstrap-server=ReelsOrbit-kafka:29092
      #- paypal-client-id=AbjzUpp06dy-_V9FgZnZUqVKQdwqKNkVI6satiVDqMgbiHVVFo0N2gw6NI9xtWNvhwRf0r5QGfJrwO8c
      #- paypal-client-secret=EAsRr46qOtOy9hgAI8fOJ2kyKhzsgvU3fqXstSHUuorAgkGgCKWouTx4oyE5Czh9hxodzKf4LPma_CfL
      #- paypal-success-url=http://localhost:8053/payments/success
      #- paypal-cancel-url=http://localhost:8053/payments/cancel
      #- payment-success-frontend-url=http://localhost:5173/paymentSuccess/
      #- paypal-cancel-frontend-url=http://localhost:5173/paymentCanceled/
    #volumes:
      #- ./reels-orbit-3f2299e99b9d.json:/app/config/credentials.json
    networks:
      - ReelsOrbit
    depends_on:
      - kafka
      - zookeeper
      - zipkin
      - mail-dev

  ReelsOrbitEmail:
    container_name: ReelsOrbit_Email
    image: radiocat2000/reels_orbit_email:latest
    environment:
      - SPRING_PROFILES_ACTIVE=doc
    networks:
      - ReelsOrbit
    ports:
      - "8054:8054"
    depends_on:
      - kafka
      - zookeeper
      - zipkin

  ReelsOrbitSecurity:
    container_name: ReelsOrbit_security
    image: radiocat2000/reels_orbit_security:latest
    environment:
      - SPRING_PROFILES_ACTIVE=doc
    networks:
      - ReelsOrbit
    ports:
      - "8080:8080"
    depends_on:
      - zipkin

  postgres:
    container_name: ReelsOrbit-postgres
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - ReelsOrbit

  zipkin:
    container_name: ReelsOrbit-zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - ReelsOrbit

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: ReelsOrbit-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ReelsOrbit

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ReelsOrbit-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://ReelsOrbit-kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - ReelsOrbit

  mail-dev:
    container_name: ReelsOrbit-mail
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  ReelsOrbit:
    driver: bridge

volumes:
  postgres: