services:
  postgres:
    container_name: ReelsOrbit-postgres
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: rod
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
volumes:
  postgres:
    driver: local